version: "3"
services:
    php:
        build: 
            context: ./docker/php
        ports:
            - 9000:9000
        volumes:
            - nfsmount:/app:delegated
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/override.ini
            - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    nginx:
        image: nginx:1.16.1
        ports:
            - 80:80
        volumes:
            - nfsmount:/app:delegated
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
    postgres:
        image: postgres:12
        ports:
            - 5432:5432
        volumes:
            - ./:/app
        environment:
            POSTGRES_DB: youtube_blog
            POSTGRES_USER: youtube_user
            POSTGRES_PASSWORD: youtube_password
volumes:
    nfsmount:
        driver: local
        driver_opts:
            type: nfs
            o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
            device: ":${PWD}"

